title: Vishnu Jayan
description: A software Engineer.
subtitle: Resourceful professional with more than 2 year experience in PHP open source technologies and website design technologies.
show_downloads: true
github:
  is_project_page: true
  url: https://github.com/itsmevishnu
  is_project_page: true
google_analytics:
theme: jekyll-theme-architect
resume: assets/doc/vishnu.pdf
# Social media links.
social:
  facebook: https://www.facebook.com/vishnu.jayadhevan
  stackoverflow: http://stackoverflow.com/users/4840468/vishnu-jayan
  linkedin: https://www.linkedin.com/in/vishnujayadhevan
  quara: https://www.quora.com/profile/Vishnu-Jayan-3
# Contact details.
contact:
  skype: vishnu.jayadhevan
  email: mailto@vishnujayan.in
# Default values.
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true
